### ISSUE TITLE
Allow Maven / Gradle to automatically retrieve CheckboxTree

### ISSUE THREAD

**Issue by maehne** [lorebiga/CheckboxTree#2]
Thanks for the development of CheckboxTree! Our educational tool [Logisim-evolution](https://github.com/reds-heig/logisim-evolution/) depends on `lablib-checkboxtree-3.3.jar` and we distributed it as part of the source code archive. Since we migrated our build tool to Gradle, we try to retrieve all build dependencies automatically. CheckboxTree is the last one without an entry on [Maven Central](https://search.maven.org/). Through a general web search, I found [this repository](https://github.com/lorebiga/CheckboxTree) and the [official home page](http://www.essi-lab.eu/projectsSites/lablib-checkboxtree/). The [Download page](https://www.essi-lab.eu/projectsSites/lablib-checkboxtree/download.html) on your home page contains information on how to set up Maven for automatically retrieving `lablib-checkboxtree`, but it does not work. Also the [direct download link](http://essi-lab.eu/nexus/index.html#nexus-search;classname~checkboxtree) is broken. It would be great if these issues could be fixed, even though there is no ongoing development activity for this library.

As a light-weight alternative solution, the build artifacts could be directly hosted on GitHub. I found a [third-party Maven repository](https://github.com/nroduit/mvn-repo) hosted on GitHub, which provides  `lablib-checkboxtree-3.3.jar` and it should be easy for you as the original developers to set up a Maven repository with the relevant releases 3.3 and 4.0-beta-1 in the same way either in a separate branch or in a separate Git repository. If CheckboxTree would be available directly through [Maven Central](https://search.maven.org/), this would be the most comfortable solution.

**Comment by lorebiga** [comment]
Version 4.0-beta-2 of the component should be available on Central https://repo1.maven.org/maven2/ within 30 minutes from now (updates to https://search.maven.org/ can take up to four hours).

Note that the code has been repackaged.

Sorry it took this long, hope it's still useful.

**Comment by maehne** [comment]
Thanks for the new release! Though, we managed to remove this dependency completely (see PR https://github.com/logisim-evolution/logisim-evolution/pull/719).

**Comment by delanym** [comment]
@lorebiga its still useful. Thanks for releasing
